accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<username>/mypage/", views.my_page, name="my_page"),
]

meeting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plans.urls')),
    path('accounts/', include('accounts.urls')),
]

plans/urls.py
from django.urls import path
from . import views

app_name = 'plans'

urlpatterns = [
    # main - 전체 페이지 조회
    path('', views.index, name='index'),

    # 30일 이후의 약속 조회
    path('coming/', views.plan_coming, name='plan_coming'),
    
    
    # 아래는 볼 필요 없음!!
    # 해당 날짜의 전체 약속 조회
    path('<int:month>/<int:day>/', views.plan_date, name='plan_date'),

    # 해당 약속 조회
    path('<int:pk>/detail/', views.plan_detail, name='plan_detail'),

    # 약속 추가
    path('create/', views.plan_create, name='plan_create'),

    # 약속 삭제
    path('<int:pk>/delete/', views.plan_delete, name='plan_delete'),

    # 약속 수정
    path('<int:pk>/update/', views.plan_update, name='plan_update'),

    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),

    # 댓글 삭제
    path('<int:plan_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),

    # 참가(좋아요) 버튼
    path('<int:plan_pk>/join_users/', views.join_users, name='join_users'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)

plans/models.py
from django.db import models
from django.conf import settings
from datetime import date

# Create your models here.

class Plan(models.Model):

    # user 정보
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 약속 제목
    title = models.CharField(max_length=20)

    # 약속 날짜
    date = models.DateField()

    # 약속 시간
    time = models.TimeField()

    # 약속 최대 인원
    people_limit = models.IntegerField() 

    # 약속 장소
    place = models.CharField(max_length=20)

    # 약속 설명
    description = models.TextField()

    # 약속 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)

    # 참가 명단
    join_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='join_plans')

    def __str__(self) -> str:
        return super().__str__()


class Comment(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ("last_name", "first_name")

accounts/views.py
from distutils.log import error
from django.shortcuts import get_object_or_404, render, redirect
from .forms import CustomUserCreationForm
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from datetime import date
from django.utils import timezone
from django.db.models import Q


@require_http_methods(["POST", "GET"])
def signup(request):
    errors = []
    if request.user.is_authenticated:
        return redirect("plans:index")
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("plans:index")
        else:
            username = request.POST.get('username')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            
            if get_user_model().objects.filter(username=username).exists():
                errors.append('중복된 아이디가 있습니다')
            
            elif password1 != password2:
                errors.append('비밀번호 확인이 틀렸습니다')
            
            elif len(password1) < 8:
                errors.append('8자 이상의 비밀번호를 입력해주세요')
            
            elif password1.isdigit() or password1.isalpha():
                errors.append('숫자와 문자를 함께 입력해주세요')
            
            else:
                errors.append('특수기호는 @ . + - _ 만 가능합니다')
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
        "errors": errors,
    }
    return render(request, "accounts/signup.html", context)


@require_http_methods(['POST', 'GET'])
def login(request):
    if request.user.is_authenticated:
        return redirect('plans:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'plans:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('plans:index')


def my_page(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    today = date.today()
    nowtime = timezone.now()
    
    coming_plans = person.join_plans.filter(Q(date__gt=today) | Q(time__gte=nowtime, date=today)).order_by('date', 'time')
    passed_plans = person.join_plans.filter(Q(date__lt=today) |Q(date=today, time__lt=nowtime)).order_by('date')
    today_plans = coming_plans.filter(date = today)

    first_plan = ''
    if today_plans:
        first_plan = today_plans[0]
    context = {
        'person': person,
        'coming_plans': coming_plans,
        'passed_plans': passed_plans,
        'today_plans': today_plans,
        'first_plan': first_plan,
    }
    return render(request, 'accounts/my_page.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'accounts/login.css' %}?after">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:index' %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}

<div class='d-flex flex-column justify-content-evenly align-items-center'>
  <h1>로그인</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    <div>
      <label class='mb-1' for="username">아이디</label>
    </div>
    <p>
      {{ form.username }}
    </p>
    <div>
      <label class='mb-1' for="password">비밀번호</label>
    </div>
    <p class='mb-4'>
      {{ form.password }}
    </p>
    <div class='d-flex flex-column align-items-center'>
    {% if form.errors %}
      <p style='color: rgb(209, 51, 0);'><img style='width:30px; height:30px;' src="{% static 'accounts/my_image.png' %}" alt="사진사진">계정을 다시 확인해 주세요</p>
    {% endif %}
    </div>
    <input class='t-3 input_button' type="submit" value='입장'>
  </form>
</div>

{% endblock content %}

accounts/templates/accounts/my_page.html
{% extends 'base.html' %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'accounts/my_page.css' %}?after" />
{% endblock style %} {% block back_button %}
<a href="{% url 'plans:index' %}"
  ><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px"></i
></a>
{% endblock back_button %} {% block content %}
<h3>Hi, {{ person.first_name }}!</h3>
<div class="details_box m-5">
  <details>
    <summary>
      <span>오늘 예정된 약속</span
      ><span class="num_badge">{{ today_plans|length }}개</span>
    </summary>
    <div class="container">
      {% if today_plans %}
      <input type="hidden" id="first-time" value="{{ first_plan.time }}" />
      <div class="left-time">
        <span>약속까지 남은 시간</span>
        <span class="time-count"></span>
      </div>
      {% for plan in today_plans %}
      <a
        class="plan_box d-flex justify-content-start align-items-center text-decoration-none text-black"
        href="{% url 'plans:plan_detail' plan.pk %}"
      >
        <p class="plan_title">{{ plan.title }}</p>
        <p class="plan_date">({{ plan.time }})</p>
      </a>
      {% endfor %} {% else %}
      <p>오늘 예정된 약속이 없습니다!</p>
      {% endif %}
    </div>
  </details>

  <details>
    <summary>
      <span>내가 작성한 약속</span
      ><span class="num_badge">{{ person.plan_set.all|length }}개</span>
    </summary>
    <div class="container">
      {% if not person.plan_set.all %}
      <p class="plan_title">작성한 약속이 없습니다</p>
      {% endif %} {% for plan in person.plan_set.all %}
      <a
        class="plan_box d-flex justify-content-start align-items-center text-decoration-none text-black"
        href="{% url 'plans:plan_detail' plan.pk %}"
      >
        <p class="plan_title">{{ plan.title }}</p>
        <p class="plan_date">({{ plan.date }})</p>
      </a>
      {% endfor %}
    </div>
  </details>

  <details>
    <summary>
      <span>앞으로 예정된 약속</span
      ><span class="num_badge">{{ coming_plans|length }}개</span>
    </summary>
    <div class="container">
      {% if not coming_plans %}
      <p class="plan_title">예정된 약속이 없습니다</p>
      {% endif %} {% for plan in coming_plans %}
      <a
        class="d-flex justify-content-start text-decoration-none text-black"
        href="{% url 'plans:plan_detail' plan.pk %}"
      >
        <p class="plan_title">{{ plan.title }}</p>
        <p class="plan_date">({{ plan.date }})</p>
      </a>
      {% endfor %}
    </div>
  </details>

  <details>
    <summary>
      <span>내가 참석했던 약속</span
      ><span class="num_badge">{{ passed_plans|length }}개</span>
    </summary>
    <div class="container">
      {% if not passed_plans %}
      <p class="plan_title">참석했던 약속이 없습니다</p>
      {% endif %} {% for plan in passed_plans %}
      <a
        class="d-flex justify-content-start text-decoration-none text-black"
        href="{% url 'plans:plan_detail' plan.pk %}"
      >
        <p class="plan_title">{{ plan.title }}</p>
        <p class="plan_date">({{ plan.date }})</p>
      </a>
      {% endfor %}
    </div>
  </details>
</div>

{% endblock content %} {% block script %}
<script>
  const timeDiv = document.querySelector(".time-count")
  const firstPlanTime = transTime(document.querySelector("#first-time").value)
  function transTime(timestr) {
    const splitTime = timestr.split(" ")
    let result = splitTime[0] === "오전" ? 0 : 720
    const clockTime = splitTime[1].split(":").map(Number)
    return result + clockTime[0] * 60 + clockTime[1]
  }

  function transStr(time) {
    return `${parseInt(time / 60)}시간 ${time % 60}분`
  }

  const timeCount = function () {
    const now = new Date()
    const nowHour = now.getHours()
    const nowMin = now.getMinutes()
    const nowTime = nowHour * 60 + nowMin

    const leftTime = firstPlanTime - nowTime
    timeDiv.innerText = transStr(leftTime)
  }

  setInterval(timeCount, 1000)
</script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  
  <link rel="stylesheet" href="{% static 'accounts/signup.css' %}?{% now 'U'%}">

{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:index' %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
  <div class='d-flex flex-column justify-content-evenly align-items-center'>
    <h1 class='my-4 main'>회원가입</h1>
    <form class='signup_form' action="{% url 'accounts:signup' %}" method="post">
      {% csrf_token %}
      <div>
        <label for="id_username">아이디</label>
      </div>
      <p>
        {{ form.username }}
      </p>
      <p style="font-size: 13px;">특수기호는 @ . + - _ 만 가능합니다</p>
      <div>
        <label for="id_password1">비밀번호</label>
      </div>
      <p>
        {{ form.password1 }}
      </p>
      <div>
        <label for="id_password2">비밀번호 확인</label>
      </div>
      <p>
        {{ form.password2 }}
      </p>
      <div>
        <label for="id_last_name">성</label>
      </div>
      <p>
        {{ form.last_name }}
      </p>
      <div>
        <label for="id_first_name">이름</label>
      </div>
      <p>
        {{ form.first_name }}
      {% for error in errors %}
        <p class='error_message' style='color: rgb(209, 51, 0);'><img style='width:30px; height:30px;' src="{% static 'accounts/my_image.png' %}" alt="사진사진">{{ error }}</p>
      {% endfor %}
      </p>
      <input class='input_button' type="submit" value="작성">
    </form>
  </div>
 
  {% comment %} </div> {% endcomment %}
{% endblock content %}