accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<username>/mypage/", views.my_page, name="my_page"),
]

meeting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plans.urls')),
    path('accounts/', include('accounts.urls')),
]

plans/urls.py
from django.urls import path
from . import views

app_name = 'plans'

urlpatterns = [
    # main - 전체 페이지 조회
    path('', views.index, name='index'),

    # 30일 이후의 약속 조회
    path('coming/', views.plan_coming, name='plan_coming'),
    
    
    # 아래는 볼 필요 없음!!
    # 해당 날짜의 전체 약속 조회
    path('<int:month>/<int:day>/', views.plan_date, name='plan_date'),

    # 해당 약속 조회
    path('<int:pk>/detail/', views.plan_detail, name='plan_detail'),

    # 약속 추가
    path('create/', views.plan_create, name='plan_create'),

    # 약속 삭제
    path('<int:pk>/delete/', views.plan_delete, name='plan_delete'),

    # 약속 수정
    path('<int:pk>/update/', views.plan_update, name='plan_update'),

    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),

    # 댓글 삭제
    path('<int:plan_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),

    # 참가(좋아요) 버튼
    path('<int:plan_pk>/join_users/', views.join_users, name='join_users'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'icon.jpg' %}"/>
    {% comment %} <link rel="shortcut icon" type="image/x-icon" href="{% static 'icon2.png' %}"/> {% endcomment %}
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <title>THUNDERMAN</title>
    <link rel="stylesheet" href="{% static 'base.css' %}?after">
    {% block style %}
    
    {% endblock style %}
</head>
<body class='d-flex flex-column align-items-center'>
<div class='base_main'>
<!-- nav bar 부분-->
<nav>
  <div class='pure_navbar'>
    <div class='nav_bar_column'>
      <div class='nav_back_button'>
        {% block back_button %}

        {% endblock back_button %}
      </div>
      {% if request.user.is_authenticated %}
        <div class='nav_button'>
          <span class='ms-4 user_name_text'><a class='nav_button_anc_hi' href='{% url 'accounts:my_page' user.username %}'>Hi,{{ user.first_name }}!</a></span>
          {% comment %} my_page의 nav버튼에 hi username을 눌렀을 때, mypage로 연결되게 했는데 어떨까요? {% endcomment %}
          {% comment %} <span class='ms-4 user_name_text'>Hi,{{ user.first_name }}!</span> {% endcomment %}
        </div>
        <div class='nav_button'>  
          <form class='nav_bar_form' class=''  action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input class='nav_button_anc nav_bar_form' type="submit" name="logout" id="logout" value="Logout">
          </form>
        </div>
      {% else %}
        <div class='nav_button'>
          <a class='nav_button_anc' href="{% url 'accounts:login' %}">Login</a>
        </div>
        <div class='nav_button'>
          <a class='nav_button_anc' href="{% url 'accounts:signup' %}">Sign up</a>
        </div>
      {% endif %}
    </div>
    <div class='nav_bar_column'>
      <a class='nav_bar_main_logo_anchor' href="{% url 'plans:index' %}">
        <span class='nav_bar_main_logo'>THUNDERMAN</span>
      </a>
    </div>
    <div class='nav_bar_column'>
      <div class='nav_button'>
        {% if request.user.is_authenticated %}
          <a class='nav_button_anc' href="{% url 'accounts:my_page' user.username %}">My Page</a>
        {% endif %}
      </div>
      <div class='nav_button'>
        <a class='nav_button_anc' href="{% url 'plans:plan_create' %}">Create</a>
      </div>
    </div>
</div>
</nav>

<!--본문-->

  <main class="container my-3" id='content'>
    {% block content %}

    {% endblock content %}
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}

</body>
</html>