accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<username>/mypage/", views.my_page, name="my_page"),
]

meeting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plans.urls')),
    path('accounts/', include('accounts.urls')),
]

plans/urls.py
from django.urls import path
from . import views

app_name = 'plans'

urlpatterns = [
    # main - 전체 페이지 조회
    path('', views.index, name='index'),

    # 30일 이후의 약속 조회
    path('coming/', views.plan_coming, name='plan_coming'),
    
    
    # 아래는 볼 필요 없음!!
    # 해당 날짜의 전체 약속 조회
    path('<int:month>/<int:day>/', views.plan_date, name='plan_date'),

    # 해당 약속 조회
    path('<int:pk>/detail/', views.plan_detail, name='plan_detail'),

    # 약속 추가
    path('create/', views.plan_create, name='plan_create'),

    # 약속 삭제
    path('<int:pk>/delete/', views.plan_delete, name='plan_delete'),

    # 약속 수정
    path('<int:pk>/update/', views.plan_update, name='plan_update'),

    # 댓글 작성
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),

    # 댓글 삭제
    path('<int:plan_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),

    # 참가(좋아요) 버튼
    path('<int:plan_pk>/join_users/', views.join_users, name='join_users'),
]

plans/models.py
from django.db import models
from django.conf import settings
from datetime import date

# Create your models here.

class Plan(models.Model):

    # user 정보
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 약속 제목
    title = models.CharField(max_length=20)

    # 약속 날짜
    date = models.DateField()

    # 약속 시간
    time = models.TimeField()

    # 약속 최대 인원
    people_limit = models.IntegerField() 

    # 약속 장소
    place = models.CharField(max_length=20)

    # 약속 설명
    description = models.TextField()

    # 약속 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)

    # 참가 명단
    join_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='join_plans')

    def __str__(self) -> str:
        return super().__str__()


class Comment(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

plans/forms.py
import datetime
from django import forms
from .models import Plan, Comment


class PlanForm(forms.ModelForm):
    # 전체적으로 보기 좋게 하기 위해 넓이는 form의 길이에 맞춘다.
    box_class = 'w-100 my-2'
    large_box_class = 'w-100 my-2'

    title = forms.CharField(
        max_length=20,
        widget= forms.TextInput(
            attrs={
                'class': box_class
                
            }
        )
    )

    date = forms.DateField(
        widget= forms.DateInput(
            attrs={
                'class': box_class,
                'type': 'date',
                'value' : datetime.date.today(),
            }
        )
    )

    time = forms.TimeField(
        widget= forms.TimeInput(
            attrs={
                'class': box_class,
                'type': 'time',
                # step은 30분 단위로 설정
                'step': '1800',
                'value' : '19:00:00',
            }
        )
    )

    people_limit = forms.IntegerField(
        widget= forms.NumberInput(
            attrs={
                'placeholder': '제한이 없을시 0을 입력해주세요',
                'min': 0,
                'class': box_class,
            }
        )
    )

    place = forms.CharField(
        max_length=20,
        widget= forms.TextInput(
            attrs={
                'class': box_class,
            }
        )
    )

    description = forms.CharField(
        widget= forms.Textarea(
            attrs={
                'placeholder': '어떤 모임인지 자세히 작성해 주세요.',
                'cols': 40,
                'rows': 10,
                'class': large_box_class,
            }
        )       
    )
    


    class Meta:
        model = Plan
        exclude = ('user', 'join_users',)


class CommentForm(forms.ModelForm):
    large_box_class = 'w-100 my-2'
    content = forms.CharField(
        widget= forms.Textarea(
            attrs={
                'placeholder': '댓글을 작성해주세요',
                'cols': 10,
                'rows': 4,
                'class': large_box_class,
            }
        )       
    )

    class Meta:
        model = Comment
        fields = ('content',)

plans/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.db.models import Count
from .models import Plan, Comment
from .forms import PlanForm, CommentForm
from datetime import date, datetime, timedelta

# Create your views here.

@require_safe
def index(request):
    # 30일 간격 조회
    startdate = date.today()
    interval = 30
    enddate = startdate + timedelta(days=interval)
    plan_cnt = Plan.objects.filter(date__range=[startdate, enddate]).values('date').annotate(total=Count('date')).order_by('date')
    endtime = datetime.now()
    starttime = endtime - timedelta(hours=24)
    plan_new = Plan.objects.filter(created_at__range=[starttime, endtime]).values_list('date', flat=True)
    context = {
        "plan_cnt": plan_cnt,
        "plan_new": plan_new,
    }
    return render(request, 'plans/index.html', context)


def plan_coming(request):
    # 그 이후의 약속 조회
    startdate = date.today()
    interval = 30
    enddate = startdate + timedelta(days=interval)

    plan_cnt = Plan.objects.filter(date__gt=enddate).values('date').annotate(total=Count('date')).order_by('date')
    
    # new 만들려고 한 거니 그대로 가져오면 된다
    endtime = datetime.now()
    starttime = endtime - timedelta(hours=24)
    plan_new = Plan.objects.filter(created_at__range=[starttime, endtime]).values_list('date', flat=True)

    context = {
        "plan_cnt": plan_cnt,
        'plan_new': plan_new,
    }

    return render(request, 'plans/plan_coming.html', context)



def plan_date(request, month, day):
    plandate = date(2022, month, day)
    plans = Plan.objects.filter(date=plandate)
    context = {
        "plans": plans,
        "plandate": plandate,
    }
    return render(request, 'plans/plan_date.html', context)


def plan_detail(request, pk):
    plan = get_object_or_404(Plan, pk=pk)
    comment_form = CommentForm()
    comments = plan.comment_set.all()
    context = {
        'plan' : plan,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'plans/plan_detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def plan_create(request):
    if request.method == "POST":
        form = PlanForm(request.POST)
        if form.is_valid():
            plan = form.save(commit=False)
            plan.user = request.user
            plan.save()
            plan.join_users.add(request.user)
            return redirect('plans:plan_detail', plan.pk)
    else:
        form = PlanForm()
    context = {
        'form': form
    }
    return render(request, 'plans/plan_create.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def plan_update(request, pk):
    plan = get_object_or_404(Plan, pk=pk)
    if plan.user == request.user:
        if request.method == 'POST':
            form = PlanForm(request.POST, instance=plan)
            if form.is_valid():
                plan = form.save()
                return redirect('plans:plan_detail', plan.pk)
        else:
            form = PlanForm(instance=plan)
    else:
        return redirect('plans:index')
    context = {
        'plan': plan,
        'form': form,
    }
    return render(request, 'plans/plan_update.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def comment_create(request, pk):
    if request.user.is_authenticated:
        plan = get_object_or_404(Plan, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.plan = plan
            comment.user = request.user
            comment.save()
        return redirect('plans:plan_detail', plan.pk)
    return redirect('accounts:login')


@require_POST
def comment_delete(request, plan_pk ,comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('plans:plan_detail', plan_pk)


@require_POST
def join_users(request, plan_pk):
    if request.user.is_authenticated:
        plan = get_object_or_404(Plan, pk=plan_pk)
        if plan.join_users.filter(pk=request.user.pk).exists():
            plan.join_users.remove(request.user)
        else:
            plan.join_users.add(request.user)
        return redirect('plans:plan_detail', plan_pk)
    return redirect('accounts:login')

@require_POST
def plan_delete(request, pk):
    plan = get_object_or_404(Plan, pk=pk)
    if request.user.is_authenticated:
        if request.user == plan.user:
            plan.delete()
    return redirect('plans:index')

plans/templates/plans/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/index.css' %}?after">
{% endblock style %}

{% block back_button %}
  <a href="#"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
<!-- 바로 아래 태그가 전체를 위 아래 중앙 정렬하는 태그이므로 이상하면 없애야 함-->
  <div class='main_box d-flex flex-column justify-content-center'>

    <div class="my-3 text-center">
      <h3 class="fw-bold"><img style='top: 3px; width: 40px; height:40px;' src="{% static 'plans/sunglass.png' %}" alt="선글라스"> 현재 당신을 기다리고 있는 약속들 <img style='top: 3px; width: 40px; height:40px;' src="{% static 'plans/sunglass.png' %}" alt="선글라스"></h3>
      <p class='mt-3'>오늘로부터 30일 이내의 약속만 조회됩니다</p>
    </div>
    <div class="container d-flex flex-column align-items-center justify-content-evenly mb-5">
      {% for plan in plan_cnt %}
        <div class='d-flex justify-content-center my-3 align-items-center'>
          <h2 class='my-1 mx-3 '>
            <a class='text-decoration-none date_font' href="{% url 'plans:plan_date' plan.date.month plan.date.day %}">
              {{ plan.date }} {{ plan.date|date:'D'}}
            </a>
          </h2> 
          <div class='badge'>
            <a class='text-decoration-none text-white' href="{% url 'plans:plan_date' plan.date.month plan.date.day %}">
              <h5 class='my-1 mx-1'>{{ plan.total }}개</h5>
              {% if plan.date in plan_new %}
              <span class="d-flex align-items-center position-absolute top-0 start-100 translate-middle badge rounded-pill badge_mini">
                New
              </span>
              {% endif %}
            </a>   
          </div>
        </div>
      {% empty %}
        <p>30일 내로 예정된 약속이 없습니다!</p>
        <a class='mt-3 day_after_create' href="{% url 'plans:plan_create' %}">새로운 약속 만들러 가기</a>
      {% endfor %}  
      <a class='mt-3 day_after' href="{% url 'plans:plan_coming' %}">그 이후의 약속 보기</a>
    </div>
  </div>
{% endblock content %}
  
  <!-- 힘들게 만든 + 버튼 -->
  
  {% comment %} <a href="{% url 'plans:plan_create' %}" class="text-decoration-none">
    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16" id="create_btn">
      <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
    </svg>
  </a> {% endcomment %}

plans/templates/plans/plan_coming.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/plan_coming.css' %}?{% now "U" %}">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:index' %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
  <div class='main_box d-flex flex-column justify-content-center'>

    <div class="my-3 text-center">
      <h3 class="fw-bold"><img style='top: 3px; width: 40px; height:40px;' src="{% static 'plans/sunglass.png' %}" alt="선글라스"> 현재 당신을 기다리고 있는 이후 약속들 <img style='top: 3px; width: 40px; height:40px;' src="{% static 'plans/sunglass.png' %}" alt="선글라스"></h3>
      <p>오늘로부터 30일 이후의 약속만 조회됩니다</p>
    </div>

    <div class="container d-flex flex-column align-items-center justify-content-evenly mb-5">
      {% for plan in plan_cnt %}
      <div class='d-flex justify-content-center my-3 align-items-center'>
        <h2 class='my-1 mx-3 '>
          <a class='text-decoration-none date_font' href="{% url 'plans:plan_date' plan.date.month plan.date.day %}">
            {{ plan.date }} {{ plan.date|date:'D'}}
          </a>
        </h2> 
        <div class='badge'>
          <a class='text-decoration-none text-white' href="{% url 'plans:plan_date' plan.date.month plan.date.day %}">
            <h5 class='my-1 mx-1'>{{ plan.total }}개</h5>
            {% if plan.date in plan_new %}
            <span class="d-flex align-items-center position-absolute top-0 start-100 translate-middle badge rounded-pill badge_mini">
              New
            </span>
            {% endif %}
          </a>   
        </div>
      </div>
      {% endfor %}  
    </div>
  </div>
{% endblock content %}

plans/templates/plans/plan_create.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/plan_create.css' %}?after ">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:index' %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
  <div class='d-flex flex-column justify-content-evenly align-items-center'>
    <h1 class='mb-4'>약속을 잡아봅시다!</h1>
    <form class='d-flex flex-column justify-content-evenly' action="{% url 'plans:plan_create' %}" method="POST">
      {% csrf_token %}
      <label for="id_title">모임의 이름을 적어주세요</label>
      <p>{{ form.title }}</p>
      <label for="id_date">만나는 날짜가 언제인가요?</label>
      <p>{{ form.date }}</p>
      <label for="id_time">몇 시에 만나나요?</label>
      <p>{{ form.time }}</p>
      <label for="id_people_limit">몇 명까지 만날 수 있나요?</label>
      <p>{{ form.people_limit }}</p>
      <label for="id_place">어디서 만나나요?</label>
      <p>{{ form.place }}</p>
      <label for="id_title">어떤 만남인가요?</label>
      <p>{{ form.description }}</p>

      <button class="submit_button" type="submit" >제출</button>
    </form>
  </div>
{% endblock content %}

plans/templates/plans/plan_date.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/index.css' %}?after">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:index' %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
<div class='d-flex flex-column align-items-center'>
  <h3 class='mb-5'>{{ plandate }}</h3>
  <table class='table table-hover'>
    <thead class='text-center text-white'>
      <tr>
        <th>제목</th>
        <th>작성자</th>
        <th>시간</th>
        <th>장소</th>
        <th>참여인원</th>
      </tr>
    </thead>
    <tbody class='text-center'>
      {% for plan in plans %}
        <tr>
          <td>
            <a href="{% url 'plans:plan_detail' plan.pk %}">{{ plan.title }}</a>
          </td>
          <td>{{ plan.user.last_name }}{{ plan.user.first_name }}</td>
          <td>{{ plan.time }}</td>
          <td>{{ plan.place }}</td>
          <td>
            {% if plan.people_limit == 0 %}
              {{ plan.join_users.all|length }}명
            {% else %}
              {{ plan.join_users.all|length }}명 / {{ plan.people_limit }}명
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

plans/templates/plans/plan_detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/plan_detail.css' %}?{% now "U" %}">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:plan_date' plan.date.month plan.date.day %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
  <div class="d-flex justify-content-between">
    <h2>{{ plan.title }}</h2>
    {% if request.user == plan.user %}
      <div class="btn-group" style="height: 40px;">
        <a href="{% url 'plans:plan_update' plan.pk %}" class="btn" id="submit-btn">수정</a>
        <button type="button" class="btn btn-danger mx-1" data-bs-toggle="modal" data-bs-target="#plandeletealert">삭제</button>
        <div class="modal fade" id="plandeletealert" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">주의!</h5>
              </div>
              <div class="modal-body">
                {% if plan.join_users.all|length %}
                  <p class="fw-bold" style="color: red;">현재 참석자가 있습니다!</p>
                {% endif %}
                <p>정말 삭제하시겠습니까?</p>
              </div>
              <div class="modal-footer">
                <form action="{% url 'plans:plan_delete' plan.pk %}" method="POST">
                  {% csrf_token %}
                  <div class="btn-group" style="height: 40px;">
                    <button type="submit" class="btn btn-danger">삭제</button>
                    <button type="button" class="btn btn-secondary mx-1" data-bs-dismiss="modal">취소</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
  <p>{{ plan.user.last_name }}{{ plan.user.first_name }}</p>
  <p>{{ plan.date }} {{ plan.date|date:'D'}} {{ plan.time }}에 {{ plan.place }}에서 만날 사람?</p>
  <p>{{ plan.description|linebreaksbr }}</p>
  <hr>


  <form action="{% url 'plans:join_users' plan.pk %}" method='POST'>
    {% csrf_token %}
    {% if request.user in plan.join_users.all %}
      <div class="btn-group">
        {% if request.user.is_authenticated %}
          <button type='submit' class='btn btn-danger'>취소</button>
        {% endif %}
        <button type="button" class="btn btn-success mx-1" data-bs-toggle="collapse" href="#collapsefriends" role="button" aria-expanded="false" aria-controls="collapseExample">{{ plan.join_users.all|length }}명</button>
        <a class="btn" data-bs-toggle="collapse" href="#collapsecomments" role="button" aria-expanded="false" aria-controls="collapseExample" id="submit-btn">
          <h6 id="btn-content"><i class="fa-solid fa-comments"></i> 댓글({{ plan.comment_set.all|length }})</h6>
        </a>
      </div>
    {% else %}
      <div class="btn-group">
        {% if request.user.is_authenticated %}
          <button type="submit" class='btn btn-success'>참석</button>
        {% endif %}
        <button type="button" class="btn btn-success mx-1" data-bs-toggle="collapse" href="#collapsefriends" role="button" aria-expanded="false" aria-controls="collapseExample">{{ plan.join_users.all|length }}명</button>
        <a class="btn" data-bs-toggle="collapse" href="#collapsecomments" role="button" aria-expanded="false" aria-controls="collapseExample" id="submit-btn">
          <h6 id="btn-content"><i class="fa-solid fa-comments"></i> 댓글({{ plan.comment_set.all|length }})</h6>
        </a>
      </div>  
    {% endif %}
  </form>

  <div class="collapse mt-3" id="collapsefriends">
    <div class='d-flex justify-content align-items-center mx-2'>
      <div class="d-flex wrap">
        {% for user in plan.join_users.all %}
          {{ user.last_name }}{{ user.first_name }}
        {% endfor %}
      </div>
    </div>
  </div>

  <!--댓글 표시 부분 -->
  <div class="collapse mt-3" id="collapsecomments">
    {% for comment in comments %}
    <div class='d-flex justify-content align-items-center mx-2 comment'>
        <p class='fw-bold m-0 d-flex flex-column justify-content-center comment_name'>{{ comment.user.first_name }}: </p> <p class='m-0'>{{ comment.content }}</p>
        {% if request.user == comment.user %}
        <form action="{% url 'plans:comment_delete' plan.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit" class='btn py-0'><i class="fa-solid fa-xmark"></i></button>
        </form>
        {% endif %}
      </div>
      {% if not forloop.last %}
        <hr class='my-0 comment_hr'>
      {% else %}
      {% endif %}
    {% endfor %}
  </div>

  {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
    <form action="{% url 'plans:comment_create' plan.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.content }}
      <div class='d-flex justify-content-end'>
        <button class='btn fw-bold' id='submit-btn' type="submit">작성</button>
      </div>
    </form>
  {% comment %} {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %} {% endcomment %}
{% endblock content %}

plans/templates/plans/plan_update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'plans/plan_create.css' %}">
{% endblock style %}

{% block back_button %}
  <a href="{% url 'plans:plan_detail' plan.pk %}"><i class="fa-solid fa-angle-left ms-3" style="color: white; height: 30px;"></i></a>
{% endblock back_button %}

{% block content %}
  <div class='d-flex flex-column justify-content-evenly align-items-center'>
    <h1 class='my-4'>글 수정하기</h1>
    <form class='d-flex flex-column justify-content-evenly' action="{% url 'plans:plan_update' plan.pk %}" method="POST">
      {% csrf_token %}
      <label for="id_title">모임의 이름을 적어주세요</label>
      <p>{{ form.title }}</p>
      <label for="id_date">만나는 날짜가 언제인가요?</label>
      <p>{{ form.date }}</p>
      <label for="id_time">몇 시에 만나나요?</label>
      <p>{{ form.time }}</p>
      <label for="id_people_limit">몇 명까지 만날 수 있나요?</label>
      <p>{{ form.people_limit }}</p>
      <label for="id_place">어디서 만나나요?</label>
      <p>{{ form.place }}</p>
      <label for="id_title">어떤 만남인가요?</label>
      <p>{{ form.description }}</p>
      <button type="submit" class="submit_button">제출</button>
    </form>
  </div>
{% endblock content %}